Added non power-of-two compressed texture support
Rinnegatamante/vitaGL pull request #48
Opened 2020-11-14 15:32 UTC by bythos14

Also added some documentation and error checking. Switched RGB DXT1 to using recently added RGB1 BC1 from vitasdk, rather than RGBA BC1.

2020-11-22 12:51 UTC, Rinnegatamante requested changes

2020-11-22 12:51 UTC, Rinnegatamante commented on source/utils/gpu_utils.c
> +		if (sceGxmTextureInitLinear(&tex->gxm_tex, texture_data, format, w, h, 0) < 0) {
Is the check here really necessary?

2020-11-22 12:51 UTC, Rinnegatamante commented on source/utils/gpu_utils.c
> +	if ((orig_w % 16 != 0) || (orig_h % 26 != 0)) {
orig_h % 26 should be 16? Also this should go under a SKIP_ERROR_HANDLING i think.

2020-11-22 12:51 UTC, Rinnegatamante commented on source/utils/gpu_utils.c
> +	if (temp[0] == NULL || temp[1] == NULL) {
SKIP_ERROR_HANDLING

2020-11-22 12:51 UTC, Rinnegatamante commented on source/utils/gpu_utils.c
> +	if (texture_data == NULL) {
SKIP_ERROR_HANDLING

2020-12-06 02:48 UTC, bythos14 commented
I'm not able to complete this PR currently, so I'll be closing it for now. If and when I get the chance, I'll try to return to it.

2020-12-06 02:48 UTC, closed without merging